language: node_js
node_js:
  - stable
dist: trusty
addons:
  sonarcloud:
    organization: "jhawk1196"
    token:
      secure: ${SONAR_TOKEN}

before_install:
  - npm i -g latest-version
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
  - npm i --build-from-resource jest
  - npm i --build-from-resource jest coveralls
  - npm run test
  - npm run coveralls