language: node_js
dist: trusty
addons:
  sonarcloud:
    organization: "jhawk1196"
    token:
      secure: 0ed4cd0592d17933dcbcf9d1677baba1d4107f4d

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
  - npm i -g jest
  - npm i -g jest coveralls
  - npm run test
  - npm run coveralls
